[package]
authors = ["PureStake"]
edition = "2018"
name = "pallet-crowdloan-rewards"
version = '0.6.0'
description = "Reward citizens who participated in a crowdloan to acquire a parachain slot o nthe backing relay chain."

[dependencies]
parity-scale-codec = { version = "2.1.1", default-features = false}
serde = { version = "1.0.101", optional = true, features = ["derive"], default-features = false }
log = { version = "0.4", default-features = false }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }

frame-support = { git = "https://github.com/axtend/axlib", default-features = false, branch = "16d1466" }
frame-system = { git = "https://github.com/axtend/axlib", default-features = false, branch = "16d1466" }
sp-core = { git = "https://github.com/axtend/axlib", default-features = false, branch = "16d1466" }
sp-runtime = { git = "https://github.com/axtend/axlib", default-features = false, branch = "16d1466" }
sp-std = { git = "https://github.com/axtend/axlib", default-features = false, branch = "16d1466" }
sp-io = { git = "https://github.com/axtend/axlib", default-features = false, branch = "16d1466" }
pallet-balances = { git = "https://github.com/axtend/axlib", default-features = false, branch = "16d1466" }
pallet-utility = { git = "https://github.com/axtend/axlib", default-features = false, branch = "16d1466" }
frame-benchmarking = { git = "https://github.com/axtend/axlib", default-features = false, branch = "16d1466", optional = true }
ed25519-dalek = { version = "1.0.1", default-features = false, features = ["u64_backend", "alloc"], optional = true }
sp-trie = { git = "https://github.com/axtend/axlib", default-features = false, branch = "16d1466", optional = true }

# These cumulus dependencies to be removed with https://github.com/PureStake/crowdloan-rewards/pull/44
cumulus-primitives-core = { git = "https://github.com/axtend/cumulus", default-features = false, branch = "ea2b71e", optional = true }
cumulus-pallet-parachain-system = { git = "https://github.com/axtend/cumulus", default-features = false, branch = "ea2b71e", optional = true }
cumulus-primitives-parachain-inherent = { git = "https://github.com/axtend/cumulus", default-features = false, branch = "ea2b71e", optional = true }

[dev-dependencies]
cumulus-test-relay-sproof-builder = { git = "https://github.com/axtend/cumulus", branch = "ea2b71e" }

[features]
default = ["std"]
std = [
    "pallet-balances/std",
    "parity-scale-codec/std",
    "pallet-utility/std",
    "frame-benchmarking/std",
    "frame-support/std",
    "frame-system/std",
    "sp-core/std",
    "sp-runtime/std",
    "serde",
    "log/std",
    "sp-std/std",
    "sp-io/std",
    "cumulus-pallet-parachain-system/std",
    "cumulus-primitives-core/std",
    "cumulus-primitives-parachain-inherent/std",
    "scale-info/std",
]
runtime-benchmarks = [
    "frame-benchmarking",
    "sp-trie",
    "ed25519-dalek",
    "cumulus-primitives-core",
    "cumulus-pallet-parachain-system",
    "cumulus-primitives-parachain-inherent",
]
